apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fastapi
  namespace: flux-system
spec:
  interval: 1m
  path: ./k8s/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system